FROM mysql:8.0

ENV TZ: America/Sao_Paulo
ENV MYSQL_ALLOW_EMPTY_PASSWORD=ok
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=docker
ENV MYSQL_PASSWORD=docker
ENV MYSQL_DATABASE=alfred_bot

COPY ./init/1.sql /docker-entrypoint-initdb.d
COPY ./data /var/lib/mysql   

EXPOSE 3306