version: '3.3'

networks:
  app-tier:
    driver: bridge

services:
  # db:
  #   container_name: mysql-db
  #   image: mysql:latest
  #   restart: unless-stopped
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     TZ: America/Sao_Paulo
  #     MYSQL_ALLOW_EMPTY_PASSWORD: ok
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     MYSQL_DATABASE: alfred_bot
  #   # expose:
  #   #   - "3308"
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - ./init:/docker-entrypoint-initdb.d
  #     - ./data:/var/lib/mysql
  #   networks:
  #     - app-tier

  alfred-bot:
    container_name: alfred-bot-new
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/alfred-bot-new/src
    ports:
      - "3001:3001"
    # depends_on:
    #   - db
      #- web
    #command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; pm2 start src/main.js --node-args='--es-module-specifier-resolution=node' --name alfred-bot && pm2-runtime start src/httpCtrl.js --node-args='--es-module-specifier-resolution=node' --name alfred-bot'
    # descomentar se for usar o mysql do docker
    environment:
      # DB_URL: mysql://docker:docker@mysql-db:3308/alfred_bot
      # NODE_ENV: development
      TZ: America/Sao_Paulo
      DB_NAME: alfred_bot
      DB_USER: dev
      DB_PASSWORD: cgbreg1719=
      DB_HOST: '89.117.32.179'
      DB_PORT: "3306"
    networks:
      - app-tier

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-tier
    # image: nginx:latest
    # ports:
    #   - 8080:80
    #   - 443:443
    # volumes:
    #   - ./src/dist:/usr/share/nginx/html
    #   - ./default.conf:/etc/nginx/conf.d/default.conf
    #   - ./ssl:/etc/letsencrypt/live/taruma.shop/
    # restart: always
    # networks:
    #   - app-tier